//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStoreWPF.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int ID { get; set; }
        public long CardNumber { get; set; }
        public int CVV { get; set; }
        public string IssueDate { get; set; }
        public int IDUser { get; set; }
        public int IDBank { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual Users Users { get; set; }
    }
}
