//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStoreWPF.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInCart
    {
        public int ID { get; set; }
        public int IDGood { get; set; }
        public int IDCart { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Stationery Stationery { get; set; }
    }
}
